name: "Daily scrape"

run-name: Daily scrape by @${{ github.actor }}

on:
  workflow_dispatch:
  schedule:
  - cron: "0 3 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute
      run: python humblebundle.py

    - name: Commit changes
      run: |
        git config --global user.email "antonio.feregrino+datasets@gmail.com"
        git config --global user.name "Antonio Feregrino"
        git add data/
        git diff --staged --quiet || git commit -m 'New entries'
        git push
